import type { PestLanguage } from '../domain/catalog';
const copy = {
  "ko": {
    "target": "병해충 종류",
    "all": "전체 병해충",
    "byType": "병해충별 기록",
    "recordOnly": "사진 접수·현장 확인",
    "scope": "종류별로 사진과 현장 확인 내용을 기록할 수 있습니다. AI 판독은 검증된 모델이 연결된 대상부터 제공됩니다.",
    "description": "병해충 의심 기록을 종류별로 모아 확인하고, 농장주와 작업자가 의견을 주고받습니다.",
    "openList": "확인 목록 보기",
    "confirmed": "해당 병해충 확인",
    "notTarget": "해당 병해충 아님",
    "suspected": "의심 기록",
    "overview": "농장 현황",
    "photoTitle": "병해충 사진 접수",
    "unknownHelp": "종류를 모르겠으면 기타·미확인을 선택해 주세요.",
    "unavailable": "AI 모델 연결 대기",
    "fieldScout": "농장 예찰",
    "managementTitle": "병해충 관리",
    "overviewIntro": "응애부터 병해·곰팡이까지, 종류별 의심 기록을 함께 살펴봐요.",
    "pestKind": "해충",
    "diseaseKind": "병해·곰팡이",
    "unknownKind": "기타·미확인",
    "cases": "건",
    "reviewNeeded": "현장 확인 필요",
    "countBasis": "저장된 확인 필요 기록 기준 · 0건은 병해충이 없다는 뜻이 아니에요.",
    "farmRequired": "농장 연결 후 종류별 기록을 확인할 수 있어요.",
    "loadFailed": "현황을 불러오지 못했어요. 새로고침해 주세요.",
    "loading": "종류별 현황을 불러오고 있어요.",
    "allRecords": "전체 기록 보기",
    "alertHelp": "의심 증상과 촬영 위치를 확인하고 현장에서 살펴본 내용을 남겨 주세요."
  },
  "vi": {
    "target": "Loại sâu bệnh",
    "all": "Tất cả sâu bệnh",
    "byType": "Ghi chép theo loại",
    "recordOnly": "Gửi ảnh · kiểm tra tại chỗ",
    "scope": "Có thể lưu ảnh và kiểm tra theo loại. AI chỉ có khi mô hình đã được kiểm chứng và kết nối.",
    "description": "Xem các ghi chép nghi ngờ theo loại và trao đổi giữa chủ trại và nhân viên.",
    "openList": "Xem danh sách",
    "confirmed": "Đã xác nhận loại này",
    "notTarget": "Không phải loại này",
    "suspected": "Ghi chép nghi ngờ",
    "overview": "Tổng quan nông trại",
    "photoTitle": "Gửi ảnh sâu bệnh",
    "unknownHelp": "Nếu chưa rõ loại, chọn Khác / chưa xác định.",
    "unavailable": "Chờ kết nối mô hình AI",
    "fieldScout": "Theo dõi nông trại",
    "managementTitle": "Quản lý sâu bệnh",
    "overviewIntro": "Xem các ghi chép nghi ngờ theo loại, từ nhện đỏ đến bệnh và nấm.",
    "pestKind": "Sâu hại",
    "diseaseKind": "Bệnh / nấm",
    "unknownKind": "Khác / chưa rõ",
    "cases": "mục",
    "reviewNeeded": "Cần kiểm tra tại chỗ",
    "countBasis": "Các ghi chép đã lưu cần kiểm tra. 0 không có nghĩa là không có sâu bệnh.",
    "farmRequired": "Kết nối nông trại để xem ghi chép theo loại.",
    "loadFailed": "Không tải được dữ liệu. Hãy làm mới.",
    "loading": "Đang tải dữ liệu theo loại.",
    "allRecords": "Xem tất cả",
    "alertHelp": "Kiểm tra triệu chứng và vị trí chụp, rồi ghi lại kết quả kiểm tra tại chỗ."
  },
  "th": {
    "target": "ชนิดศัตรูพืชหรือโรค",
    "all": "ทุกชนิด",
    "byType": "บันทึกแยกตามชนิด",
    "recordOnly": "ส่งภาพ · ตรวจในพื้นที่",
    "scope": "บันทึกภาพและผลตรวจแยกตามชนิดได้ AI จะให้บริการเมื่อเชื่อมต่อโมเดลที่ผ่านการตรวจสอบแล้ว",
    "description": "ดูบันทึกที่สงสัยแยกตามชนิด และแลกเปลี่ยนความคิดเห็นระหว่างเจ้าของฟาร์มกับคนงาน",
    "openList": "ดูรายการตรวจ",
    "confirmed": "ยืนยันชนิดนี้",
    "notTarget": "ไม่ใช่ชนิดนี้",
    "suspected": "บันทึกที่สงสัย",
    "overview": "ภาพรวมฟาร์ม",
    "photoTitle": "ส่งภาพศัตรูพืชหรือโรค",
    "unknownHelp": "หากไม่ทราบชนิด ให้เลือก อื่น ๆ / ยังไม่ทราบ",
    "unavailable": "รอเชื่อมต่อโมเดล AI",
    "fieldScout": "ตรวจแปลง",
    "managementTitle": "จัดการศัตรูพืชและโรค",
    "overviewIntro": "ดูบันทึกที่สงสัยแยกตามชนิด ตั้งแต่ไรแดงไปจนถึงโรคและเชื้อรา",
    "pestKind": "ศัตรูพืช",
    "diseaseKind": "โรค / เชื้อรา",
    "unknownKind": "อื่น ๆ / ยังไม่ทราบ",
    "cases": "รายการ",
    "reviewNeeded": "ต้องตรวจในพื้นที่",
    "countBasis": "จำนวนบันทึกที่ต้องตรวจ 0 รายการไม่ได้หมายความว่าไม่มีศัตรูพืช",
    "farmRequired": "เชื่อมต่อฟาร์มเพื่อดูบันทึกแยกตามชนิด",
    "loadFailed": "โหลดข้อมูลไม่ได้ กรุณารีเฟรช",
    "loading": "กำลังโหลดข้อมูลแยกตามชนิด",
    "allRecords": "ดูบันทึกทั้งหมด",
    "alertHelp": "ตรวจอาการและตำแหน่งถ่ายภาพ แล้วบันทึกสิ่งที่พบในพื้นที่"
  },
  "zh-CN": {
    "target": "病虫害种类",
    "all": "全部病虫害",
    "byType": "按种类记录",
    "recordOnly": "提交照片·现场确认",
    "scope": "可按种类保存照片与现场检查记录。AI仅在经过验证的模型接入后提供。",
    "description": "按种类查看疑似病虫害记录，农场主和工作人员可相互交流。",
    "openList": "查看确认列表",
    "confirmed": "确认该病虫害",
    "notTarget": "并非该病虫害",
    "suspected": "疑似记录",
    "overview": "农场概况",
    "photoTitle": "提交病虫害照片",
    "unknownHelp": "不清楚种类时请选择其他／未确认。",
    "unavailable": "等待接入AI模型",
    "fieldScout": "农场巡查",
    "managementTitle": "病虫害管理",
    "overviewIntro": "从叶螨到病害、真菌，按种类一起查看疑似记录。",
    "pestKind": "虫害",
    "diseaseKind": "病害／真菌",
    "unknownKind": "其他／未确认",
    "cases": "条",
    "reviewNeeded": "需要现场确认",
    "countBasis": "基于已保存的待确认记录。0条不代表不存在病虫害。",
    "farmRequired": "连接农场后可查看各类记录。",
    "loadFailed": "无法加载，请刷新。",
    "loading": "正在加载各类数据。",
    "allRecords": "查看全部记录",
    "alertHelp": "确认疑似症状和拍摄位置，记录现场检查结果。"
  }
} as const;
export function pestText(language: PestLanguage, key: keyof typeof copy.ko) { return copy[language][key]; }
